service: funcionario-serveless-dynamo


frameworkVersion: '3'

provider:
  name: aws
  runtime: go1.x
  stage: dev
  region: us-east-1
  iam:
    role:
      statements:
       -  Effect: Allow
          Action:
            -   dynamodb:PutItem
            -   dynamodb:Scan
          Resource: 
            -   "arn:aws:dynamodb:${aws:region}:${accountId}:table/Funcionarios"



package:
  patterns:
    - '!./**'
    - ./bin/**

functions:
  insert:
    handler: bin/InsertProduct
    events:
      - httpApi:
          path: /funcionario
          method: post
  
  list:
    handler: bin/ListProducts
    events:
      - httpApi:
          path: /funcionario
          method: get

resources:
  Resources:
    FuncionariosTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Funcionarios
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
